// Generated by Unloop
// System Info Display

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_refresh_clicked(|| {
        println!("refresh clicked");
    });
    

    
    app.run()
}
